### ISSUE TITLE
Visibility of text

### ISSUE THREAD

**Issue by Brionne** [JoanZapata/android-pdfview#57]
The library is good, however the text visibility is poor even when zooming. 
Are you has a solution?

**Comment by janpieper** [comment]
Do you have any news on this issue? We have the same issue when zooming. The text becomes unreadable.

**Comment by rashidmoidu** [comment]
Yes ...The text become unreadable when you zoom...
any solutions?

**Comment by umairvatao** [comment]
Quote: "UPDATE: I Fixed it :)
this has done the trick:

paint.setAntiAlias(true);
paint.setFilterBitmap(true);
paint.setDither(true);

now the Text is rendered smoothly without looking broken."

How can I get "paint" object here?

**Comment by cbcnos** [comment]
I'm having the same issue here, after some observation I realised that the library is always rendering the top right corner (in horizontal swipe). This area is perfectly rendered, but none of the others are. I tried to use the paint properties and have no sucess. Also the GRID_SIZE constant just render a bigger area, but don't solves the problem.
I think there is a problem while calculating the zoomed area to be redered, but the minimap still showing the right one (the place i'm looking at). My device is a Galaxy S5 G900M.
If I can help anyway please tell me.
Thank you

**Comment by geocf** [comment]
#145 should fix this issue
KR

**Comment by yannickgagne** [comment]
Can someone tell me where to make those modifications?

paint.setAntiAlias(true);
paint.setFilterBitmap(true);
paint.setDither(true);

I have the latest pdfview source in my project but I still have the unreadable text problem sometimes.

Thanks @JoanZapata @BigJenson

**Comment by IkkarionCross** [comment]
I have the same problem. I already tried to change the GRID_SIZE and change properties of paint object.
Can someone help?

@yannickgagne the paint object is defined in the constructor of PDFView

**Comment by Shinthings** [comment]
hi, i have read how to solve this issue. but i can't, how to add :
paint.setAntiAlias(true);
paint.setFilterBitmap(true);
paint.setDither(true);

at PDFView.java

or change the GRID_SIZE to 10 in Constant.

maybe anyone can help me. thanks before

**Comment by IkkarionCross** [comment]
@Shinthings read my last post. To change GRID_SIZE go to Constants.java the declaration is there.

**Comment by Shinthings** [comment]
@IkkarionCross thanks for your response, ya how can i change the GRID_SIZE ? the file is locked / read only files. thats my problem
